# Generated by Django 6.0.2 on 2026-02-23 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0006_alter_directory_editability_and_more'),
        ('pages', '0006_alter_page_editability_alter_page_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_locks', to='directories.directory')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_locks', to='pages.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['page', 'expires_at'], name='editlock_page_expires'), models.Index(fields=['directory', 'expires_at'], name='editlock_dir_expires')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('directory__isnull', True), ('page__isnull', False)), models.Q(('directory__isnull', False), ('page__isnull', True)), _connector='OR'), name='editlock_exactly_one_target')],
            },
        ),
    ]
