# Generated by Django 6.0.2 on 2026-10-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alloweddomain_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courtlistener_sub',
            field=models.CharField(blank=True, help_text='The CourtListener account linked to this user.', max_length=64, null=True, unique=True),
        ),
    ]
