# Generated by Django 6.0.2 on 2026-03-11 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0006_alter_directory_editability_and_more'),
        ('pages', '0008_soft_delete_pages'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='directories.directory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'directory')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_exclusions', to='directories.directory')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_exclusions', to='pages.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_exclusions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('directory__isnull', True), ('page__isnull', False)), models.Q(('directory__isnull', False), ('page__isnull', True)), _connector='OR'), name='exclusion_has_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('page__isnull', False)), fields=('user', 'page'), name='unique_user_page_exclusion'), models.UniqueConstraint(condition=models.Q(('directory__isnull', False)), fields=('user', 'directory'), name='unique_user_dir_exclusion')],
            },
        ),
    ]
