# Generated by Django 6.0.2 on 2026-07-24 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_page_history_is_public'),
        ('subscriptions', '0005_remove_subscriptionexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_subscriptions', to='pages.page')),
            ],
            options={
                'unique_together': {('page', 'email')},
            },
        ),
    ]
