"""Search page and revision content for a regex pattern.

Examples:
    # Find all pages referencing a specific file ID
    python manage.py search_content '/files/42/'

    # Case-insensitive search across pages and revisions
    python manage.py search_content 'TODO|FIXME' --revisions -i

    # Find broken file references (files deleted from DB/S3)
    python manage.py search_content --broken-files

    # Show broken files with full detail including revision history
    python manage.py search_content --broken-files --revisions
"""

import re

from django.core.management.base import BaseCommand

from wiki.pages.models import FileUpload, Page, PageRevision

# Matches /files/<id>/<filename> as generated by _file_upload_markdown()
FILE_REF_RE = re.compile(r"/files/(\d+)/([^\s\)\"'\]]+)")


class Command(BaseCommand):
    help = "Search page content for a regex pattern or find broken file references."

    def add_arguments(self, parser):
        parser.add_argument(
            "pattern",
            nargs="?",
            help="Regex pattern to search for in page content.",
        )
        parser.add_argument(
            "--revisions",
            action="store_true",
            help="Also search PageRevision content (not just current pages).",
        )
        parser.add_argument(
            "-i",
            "--ignorecase",
            action="store_true",
            help="Case-insensitive pattern matching.",
        )
        parser.add_argument(
            "--broken-files",
            action="store_true",
            help=(
                "Find /files/<id>/ references in page content where the "
                "FileUpload row no longer exists in the database."
            ),
        )

    def handle(self, *args, **options):
        if options["broken_files"]:
            self._find_broken_files(options)
        elif options["pattern"]:
            self._search_pattern(options)
        else:
            self.stderr.write(
                self.style.ERROR(
                    "Provide a search pattern or use --broken-files."
                )
            )

    def _search_pattern(self, options):
        flags = re.IGNORECASE if options["ignorecase"] else 0
        try:
            regex = re.compile(options["pattern"], flags)
        except re.error as e:
            self.stderr.write(self.style.ERROR(f"Invalid regex: {e}"))
            return

        count = 0
        for page in Page.objects.iterator():
            matches = list(regex.finditer(page.content))
            if matches:
                count += 1
                self.stdout.write(
                    self.style.SUCCESS(f"\n{page.title}")
                    + f"  ({page.content_path})"
                )
                for m in matches:
                    self._print_match_context(page.content, m)

        if options["revisions"]:
            rev_count = 0
            for rev in PageRevision.objects.select_related("page").iterator():
                matches = list(regex.finditer(rev.content))
                if matches:
                    rev_count += 1
                    self.stdout.write(
                        self.style.SUCCESS(
                            f"\n{rev.page.title} (rev {rev.revision_number})"
                        )
                        + f"  ({rev.page.content_path})"
                    )
                    for m in matches:
                        self._print_match_context(rev.content, m)
            self.stdout.write(
                f"\nMatched {count} page(s) and {rev_count} revision(s)."
            )
        else:
            self.stdout.write(f"\nMatched {count} page(s).")

    def _find_broken_files(self, options):
        # Collect all file references from current page content
        page_refs = {}  # file_id -> [(page, filename)]
        for page in Page.objects.iterator():
            for m in FILE_REF_RE.finditer(page.content):
                file_id = int(m.group(1))
                filename = m.group(2)
                page_refs.setdefault(file_id, []).append((page, filename))

        # Optionally also scan revisions
        rev_refs = {}  # file_id -> [(rev, filename)]
        if options["revisions"]:
            for rev in (
                PageRevision.objects.select_related("page").iterator()
            ):
                for m in FILE_REF_RE.finditer(rev.content):
                    file_id = int(m.group(1))
                    filename = m.group(2)
                    rev_refs.setdefault(file_id, []).append((rev, filename))

        all_ids = set(page_refs.keys()) | set(rev_refs.keys())
        if not all_ids:
            self.stdout.write("No file references found in content.")
            return

        existing_ids = set(
            FileUpload.objects.filter(id__in=all_ids).values_list(
                "id", flat=True
            )
        )
        broken_ids = all_ids - existing_ids

        if not broken_ids:
            self.stdout.write(
                self.style.SUCCESS(
                    f"All {len(all_ids)} file reference(s) are valid."
                )
            )
            return

        self.stdout.write(
            self.style.WARNING(
                f"\nFound {len(broken_ids)} broken file reference(s) "
                f"(out of {len(all_ids)} total):\n"
            )
        )

        for file_id in sorted(broken_ids):
            self.stdout.write(self.style.ERROR(f"  File ID {file_id}:"))
            for page, filename in page_refs.get(file_id, []):
                self.stdout.write(
                    f"    Page: {page.title}  ({page.content_path})"
                    f"  — {filename}"
                )
            for rev, filename in rev_refs.get(file_id, []):
                self.stdout.write(
                    f"    Rev:  {rev.page.title} rev {rev.revision_number}"
                    f"  ({rev.page.content_path})"
                    f"  — {filename}"
                )

        self.stdout.write(
            f"\n{len(broken_ids)} broken / "
            f"{len(existing_ids)} valid / "
            f"{len(all_ids)} total file reference(s)."
        )

    def _print_match_context(self, text, match):
        """Print the line containing a match with the match highlighted."""
        start = text.rfind("\n", 0, match.start()) + 1
        end = text.find("\n", match.end())
        if end == -1:
            end = len(text)
        line = text[start:end]
        self.stdout.write(f"    {line.strip()}")
