# Generated by Django 6.0.2 on 2026-02-21 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('directories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directorypermission',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='directorypermission',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('directory', 'user', 'permission_type'), name='unique_dir_user_perm'),
        ),
        migrations.AddConstraint(
            model_name='directorypermission',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('directory', 'group', 'permission_type'), name='unique_dir_group_perm'),
        ),
    ]
