# Generated by Django 6.0.2 on 2026-02-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_update_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
