# Generated by Django 6.0.2 on 2026-02-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_directory_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'FLP View Only'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
