# Generated by Django 6.0.2 on 2026-02-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0004_add_internal_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='editability',
            field=models.CharField(choices=[('restricted', 'Restricted'), ('internal', 'FLP Editable')], default='restricted', max_length=10),
        ),
    ]
