# Generated by Django 6.0.2 on 2026-02-22 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_add_editability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='editability',
            field=models.CharField(choices=[('restricted', 'Restricted'), ('internal', 'FLP Staff')], default='restricted', max_length=10),
        ),
        migrations.AlterField(
            model_name='directory',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'FLP Staff'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.CreateModel(
            name='DirectoryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(max_length=10)),
                ('editability', models.CharField(max_length=10)),
                ('change_message', models.CharField(blank=True, max_length=500)),
                ('revision_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='directories.directory')),
            ],
            options={
                'ordering': ['-revision_number'],
                'unique_together': {('directory', 'revision_number')},
            },
        ),
    ]
