# Generated by Django 6.0.2 on 2026-03-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0006_alter_directory_editability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='in_llms_txt',
            field=models.CharField(choices=[('exclude', 'Exclude'), ('include', 'Include'), ('optional', 'Optional')], default='exclude', help_text="Whether to list this directory's pages in llms.txt. Excluding a directory also excludes all its children.", max_length=10),
        ),
        migrations.AddField(
            model_name='directory',
            name='in_sitemap',
            field=models.BooleanField(default=True, help_text='Include this directory in the sitemap.xml file. Excluding a directory also excludes all its children.'),
        ),
    ]
