# Generated by Django 6.0.2 on 2026-08-21 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directories", "0012_directory_seo_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectoryRedirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_path", models.CharField(max_length=500, unique=True)),
                (
                    "directory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_redirects",
                        to="directories.directory",
                    ),
                ),
            ],
        ),
    ]
