# Generated by Django 6.0.2 on 2026-02-21 16:24

from django.conf import settings
from django.db import migrations, models


def convert_restricted_to_private(apps, schema_editor):
    Page = apps.get_model("pages", "Page")
    Page.objects.filter(visibility="restricted").update(
        visibility="private"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            convert_restricted_to_private,
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='pagepermission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='page',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='pagepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('page', 'user', 'permission_type'), name='unique_page_user_perm'),
        ),
        migrations.AddConstraint(
            model_name='pagepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('page', 'group', 'permission_type'), name='unique_page_group_perm'),
        ),
    ]
