# Generated by Django 6.0.2 on 2026-02-22 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_add_editability'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='pages.page')),
                ('to_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='pages.page')),
            ],
            options={
                'unique_together': {('from_page', 'to_page')},
            },
        ),
    ]
