# Generated by Django 6.0.2 on 2026-02-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_add_page_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='editability',
            field=models.CharField(choices=[('restricted', 'Restricted'), ('internal', 'FLP Staff')], default='restricted', max_length=10),
        ),
        migrations.AlterField(
            model_name='page',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'FLP Staff'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
