# Generated by Django 6.0.2 on 2026-03-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_soft_delete_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(max_length=1000, upload_to='uploads/%Y/%m/'),
        ),
    ]
