# Generated by Django 6.0.2 on 2026-03-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_page_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Short summary for search engines and llms.txt. If blank, auto-generated from content.', max_length=300),
        ),
    ]
