# Generated by Django 6.0.2 on 2026-03-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_add_seo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='in_llms_txt',
            field=models.CharField(choices=[('exclude', 'Exclude'), ('include', 'Include'), ('optional', 'Optional')], default='exclude', help_text='Whether to list this page in llms.txt.', max_length=10),
        ),
        migrations.AddField(
            model_name='page',
            name='in_sitemap',
            field=models.BooleanField(default=True, help_text='Include this page in the sitemap.xml file.'),
        ),
    ]
