# Generated by Django 6.0.2 on 2026-03-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_add_sitemap_llms_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='in_llms_txt',
            field=models.CharField(choices=[('exclude', 'No'), ('include', 'Yes'), ('optional', 'On request')], default='exclude', help_text='Whether to list this page in llms.txt.', max_length=10),
        ),
    ]
