# Generated by Django 6.0.2 on 2026-03-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_fix_lowercase_boolean_sitemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='data_source_ttl',
            field=models.PositiveIntegerField(default=300, help_text='How many seconds to cache the data source response.'),
        ),
        migrations.AddField(
            model_name='page',
            name='data_source_url',
            field=models.URLField(blank=True, help_text="URL returning JSON whose values replace [[ key ]] placeholders in this page's content.", max_length=500),
        ),
    ]
