# Generated by Django 6.0.2 on 2026-04-21 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_slug_redirect_directory(apps, schema_editor):
    """Set SlugRedirect.directory to match the current page's directory.

    Best-effort backfill: historical SlugRedirects didn't track which
    directory the old slug was in, so we assume the redirect belongs to
    the page's current directory (true unless the page moved between
    directories while also changing slug, which is uncommon).
    """
    SlugRedirect = apps.get_model("pages", "SlugRedirect")
    for redirect in SlugRedirect.objects.select_related("page").all():
        redirect.directory_id = redirect.page.directory_id
        redirect.save(update_fields=["directory"])


class Migration(migrations.Migration):
    dependencies = [
        ("directories", "0010_fix_lowercase_boolean_sitemap"),
        ("pages", "0017_fileupload_optimization_gain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="page",
            name="unique_active_slug",
        ),
        migrations.AddField(
            model_name="slugredirect",
            name="directory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slug_redirects",
                to="directories.directory",
            ),
        ),
        migrations.AlterField(
            model_name="slugredirect",
            name="old_slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.RunPython(
            backfill_slug_redirect_directory,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("directory", "slug"),
                name="unique_active_slug_per_directory",
            ),
        ),
        migrations.AddConstraint(
            model_name="slugredirect",
            constraint=models.UniqueConstraint(
                fields=("directory", "old_slug"),
                name="unique_slug_redirect_per_directory",
            ),
        ),
    ]
