# Generated by Django 6.0.2 on 2026-06-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_pagepermission_domain_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroResultSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text="Normalized query text: lowercased, whitespace-collapsed, and tokens alphabetized so word order doesn't matter.", max_length=255)),
                ('audience', models.CharField(choices=[('staff', 'Staff'), ('public', 'Public')], max_length=10)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'zero result searches',
                'ordering': ['-count', '-last_seen'],
                'constraints': [models.UniqueConstraint(fields=('query', 'audience'), name='unique_zero_result_query_audience')],
            },
        ),
    ]
