# Generated by Django 6.0.2 on 2026-07-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_rebuild_search_vectors_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='history_is_public',
            field=models.BooleanField(default=False, help_text='Allow anyone who can view this page to see its revision history.'),
        ),
    ]
